from django.conf import settings

PAGINATION_SETTINGS = getattr(settings, 'PAGINATION_SETTINGS', {})

PAGE_RANGE_DISPLAYED = PAGINATION_SETTINGS.get('PAGE_RANGE_DISPLAYED', 10)
MARGIN_PAGES_DISPLAYED = PAGINATION_SETTINGS.get('MARGIN_PAGES_DISPLAYED', 2)
